import {
  componentLibraryRegistry,
  type ComponentLibraryEntry,
} from '@core/component-library'
import {
  accessibilityCheck,
  accessibleNameCheck,
  behaviorCheck,
  htmlTagField,
  primitiveEntry,
  providerFallbackCheck,
  textField,
} from './componentLibraryDefinitions'
import { BUILT_IN_FORM_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryForms'
import { BUILT_IN_FORM_PATTERN_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryFormPatternEntries'
import { BUILT_IN_FORM_VISUAL_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryFormVisualComponents'
import { BUILT_IN_INTERACTIVE_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryInteractiveVisualComponents'
import { BUILT_IN_PATTERN_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryPatterns'
import { BUILT_IN_VISUAL_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryVisualComponents'
import { BUILT_IN_DESIGN_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryDesignVisualComponents'
import { BUILT_IN_CAPABILITY_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryCapabilityEntries'
import { BUILT_IN_TEMPLATE_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryTemplateComponents'
import { BUILT_IN_CANONICAL_VISUAL_COMPONENT_LIBRARY_ENTRIES } from './componentLibraryCanonicalVisualComponents'

export const BUILT_IN_COMPONENT_LIBRARY_ENTRIES: readonly ComponentLibraryEntry[] = [
  ...BUILT_IN_TEMPLATE_COMPONENT_LIBRARY_ENTRIES,
  primitiveEntry({
    id: 'base.section',
    name: 'Section',
    description: 'A semantic section that groups related page content.',
    category: 'Structure',
    icon: 'layout-columns',
    moduleId: 'base.container',
    tags: ['section', 'layout', 'structure'],
    preset: {
      id: 'section',
      name: 'Section',
      values: { tag: 'section' },
    },
    usage: 'Group content that belongs under one heading or purpose.',
    accessibility: 'Give each major section an identifying heading.',
  }),
  primitiveEntry({
    id: 'base.container',
    name: 'Container',
    description: 'A neutral content container with a controlled semantic element.',
    category: 'Structure',
    icon: 'layout-columns',
    moduleId: 'base.container',
    tags: ['container', 'layout', 'group'],
    fields: [htmlTagField],
    usage: 'Group content when no more specific catalogue entry applies.',
    accessibility: 'Choose a semantic element only when it matches the content purpose.',
  }),
  primitiveEntry({
    id: 'base.heading',
    name: 'Heading',
    description: 'A section heading using the shared text implementation.',
    category: 'Typography',
    icon: 'text-heading',
    moduleId: 'base.text',
    tags: ['heading', 'title', 'text'],
    fields: [textField, htmlTagField],
    preset: {
      id: 'heading',
      name: 'Heading',
      values: { text: 'Heading', tag: 'h2' },
    },
    accessibilityChecks: [
      accessibleNameCheck('text'),
      accessibilityCheck(
        'a11y.heading-order',
        'heading',
        'automated',
        'Heading levels should not skip a level in page order.',
        'Choose the next logical heading level based on document structure.',
        ['tag'],
      ),
    ],
    usage: 'Introduce a page or section with a meaningful heading.',
    accessibility: 'Keep heading levels logical and do not choose a level for visual size alone.',
  }),
  primitiveEntry({
    id: 'base.plain-text',
    name: 'Plain Text',
    description: 'A semantic paragraph or short text fragment.',
    category: 'Typography',
    icon: 'content-text',
    moduleId: 'base.text',
    tags: ['paragraph', 'copy', 'text'],
    fields: [textField, htmlTagField],
    preset: {
      id: 'paragraph',
      name: 'Paragraph',
      values: { text: 'Add your text here.', tag: 'p' },
    },
    usage: 'Use for short plain-text content that does not need rich formatting.',
    accessibility: 'Use semantic elements that match the content rather than its appearance.',
  }),
  primitiveEntry({
    id: 'base.rich-text',
    name: 'Rich Text',
    description: 'Sanitised formatted editorial content with one semantic wrapper.',
    category: 'Typography',
    icon: 'content-text',
    moduleId: 'base.rich-text',
    tags: ['rich text', 'editorial', 'formatting', 'quotation'],
    fields: [
      { key: 'html', label: 'Content', type: 'rich-text', required: true },
      { key: 'tag', label: 'Semantic wrapper', type: 'select', required: true },
    ],
    usage: 'Use for paragraphs, lists, links, quotations and inline formatting that belong together.',
    accessibility: 'Retain a logical heading structure and descriptive link text inside the formatted content.',
  }),
  primitiveEntry({
    id: 'base.code-block',
    name: 'Code / Preformatted Text',
    description: 'Whitespace-preserving text with safe language metadata.',
    category: 'Typography',
    icon: 'file-text-solid',
    moduleId: 'base.code-block',
    tags: ['code', 'preformatted', 'snippet', 'example'],
    fields: [
      { key: 'code', label: 'Code or preformatted text', type: 'text', required: true },
      { key: 'language', label: 'Language', type: 'text', required: true },
      { key: 'label', label: 'Accessible label', type: 'text', required: true },
      { key: 'wrap', label: 'Wrap long lines', type: 'boolean', required: false },
    ],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Use for source code, command output or any content where whitespace is meaningful.',
    accessibility: 'Name the example and enable wrapping when horizontal scrolling would make it difficult to read.',
  }),
  primitiveEntry({
    id: 'base.image',
    name: 'Image',
    description: 'An image selected from the Media Library.',
    category: 'Media',
    icon: 'image',
    moduleId: 'base.image',
    tags: ['image', 'photo', 'media'],
    fields: [
      { key: 'src', label: 'Image', type: 'image', required: true },
      { key: 'loading', label: 'Loading', type: 'select', required: true },
      { key: 'fetchPriority', label: 'Fetch priority', type: 'select', required: true },
    ],
    accessibilityChecks: [
      accessibilityCheck(
        'a11y.image-alternative',
        'media',
        'manual',
        'Image alternative text must match the authored context.',
        'Review the Media Library alternative text and mark decorative images appropriately.',
      ),
    ],
    usage: 'Use an uploaded asset with loading behavior appropriate to its page position.',
    accessibility: 'Provide meaningful alternative text in the Media Library or mark decorative images.',
  }),
  primitiveEntry({
    id: 'base.button',
    name: 'Button',
    description: 'A call to action rendered as a button or link.',
    category: 'Interactive',
    icon: 'button',
    moduleId: 'base.button',
    tags: ['button', 'action', 'link', 'cta'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'href', label: 'Destination', type: 'url', required: false },
      { key: 'target', label: 'Open in', type: 'select', required: true },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    accessibilityChecks: [
      accessibleNameCheck('label'),
      accessibilityCheck(
        'a11y.touch-target',
        'touch',
        'manual',
        'The rendered action needs an adequate touch target.',
        'Verify the final design provides sufficient target size and spacing.',
      ),
      accessibilityCheck(
        'a11y.contrast',
        'contrast',
        'manual',
        'Text, focus and disabled states require sufficient contrast.',
        'Review the final token combination in every supported theme and state.',
      ),
    ],
    usage: 'Use for an action or prominent navigation destination.',
    accessibility: 'Use a specific label that describes the result of activating the control.',
  }),
  primitiveEntry({
    id: 'base.link',
    name: 'Link',
    description: 'An inline or grouped navigation link.',
    category: 'Interactive',
    icon: 'link',
    moduleId: 'base.link',
    tags: ['link', 'navigation', 'anchor'],
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'href', label: 'Destination', type: 'url', required: true },
      { key: 'target', label: 'Open in', type: 'select', required: true },
    ],
    accessibilityChecks: [accessibleNameCheck('text')],
    usage: 'Use for navigation within text or a group of linked content.',
    accessibility: 'Link text must make sense without relying on surrounding prose.',
  }),
  primitiveEntry({
    id: 'base.search',
    name: 'Search Results',
    description: 'Index-backed search across eligible published pages.',
    category: 'Content',
    icon: 'search',
    moduleId: 'base.loop',
    tags: ['search', 'results', 'index', 'collection'],
    preset: {
      id: 'published-pages',
      name: 'Published pages',
      values: {
        sourceMode: 'dynamic',
        sourceId: 'search.pages',
        manualItems: [],
        filters: {},
        orderBy: 'relevance',
        direction: 'desc',
        limit: 100,
        offset: 0,
        query: '',
        itemRenderer: 'search-result',
        pagination: 'numbered',
        pageSize: 10,
        tag: 'div',
        customTag: '',
      },
    },
    requirements: {
      capabilities: ['search.index'],
      providerAdapters: [],
      plugins: [],
    },
    accessibilityChecks: [
      behaviorCheck(
        'a11y.announcement-contract',
        'naming',
        'Search result counts, empty results and failures require a polite announcement.',
        'Verify the shared collection status announces each result state.',
      ),
    ],
    usage: 'Enable published-page search in Settings, then place this result collection on a search page.',
    accessibility: 'Pair results with a labelled GET search form whose field name matches the configured query parameter.',
  }),
  primitiveEntry({
    id: 'base.semantic-list',
    name: 'Simple List',
    description: 'An ordered or unordered semantic list.',
    category: 'Typography',
    icon: 'list-box',
    moduleId: 'base.list',
    tags: ['list', 'ordered', 'unordered'],
    fields: [
      { key: 'items', label: 'Items', type: 'text', required: true },
      { key: 'listType', label: 'List type', type: 'select', required: true },
    ],
    usage: 'Use for a sequence or group of related short items.',
    accessibility: 'Use an ordered list when item order carries meaning.',
  }),
  primitiveEntry({
    id: 'base.audio',
    name: 'Audio',
    description: 'A native audio player with an accessible title and transcript link.',
    category: 'Media',
    icon: 'video',
    moduleId: 'base.audio',
    tags: ['audio', 'media', 'recording', 'transcript'],
    fields: [
      { key: 'source', label: 'Audio file', type: 'url', required: true },
      { key: 'title', label: 'Audio title', type: 'text', required: true },
      { key: 'transcriptUrl', label: 'Transcript URL', type: 'url', required: false },
      { key: 'transcriptLabel', label: 'Transcript link label', type: 'text', required: false },
      { key: 'loop', label: 'Loop', type: 'boolean', required: false, advanced: true },
      { key: 'preload', label: 'Preload', type: 'select', required: true, advanced: true },
    ],
    accessibilityChecks: [
      accessibleNameCheck('title'),
      accessibilityCheck(
        'a11y.no-javascript-fallback',
        'media',
        'manual',
        'Spoken audio needs an equivalent transcript when required.',
        'Link a complete transcript and describe important non-speech audio.',
        ['transcriptUrl'],
      ),
    ],
    usage: 'Use for a site-hosted or HTTPS recording with native playback controls.',
    accessibility: 'Provide a specific title and a transcript for spoken information.',
  }),
  primitiveEntry({
    id: 'base.youtube-embed',
    name: 'YouTube Embed',
    description: 'A consent-delayed privacy-enhanced YouTube video.',
    category: 'Media',
    icon: 'video',
    moduleId: 'base.provider-embed',
    tags: ['video', 'youtube', 'provider', 'consent'],
    fields: [
      { key: 'sourceUrl', label: 'YouTube URL', type: 'url', required: true },
      { key: 'title', label: 'Accessible title', type: 'text', required: true },
      { key: 'fallbackText', label: 'Fallback text', type: 'text', required: true },
    ],
    preset: {
      id: 'youtube',
      name: 'YouTube',
      values: {
        adapterId: 'media.youtube',
        kind: 'media',
        title: 'YouTube video',
        fallbackText: 'YouTube video unavailable.',
      },
    },
    requirements: {
      capabilities: [],
      providerAdapters: ['media.youtube'],
      plugins: [],
    },
    accessibilityChecks: [
      providerFallbackCheck(),
      behaviorCheck(
        'a11y.focus-contract',
        'focus',
        'Consent activation and the loaded player must preserve a predictable focus path.',
        'Verify focus remains visible and does not move unexpectedly when the provider loads.',
      ),
    ],
    usage: 'Paste an approved YouTube URL; the player loads only after marketing consent or explicit activation.',
    accessibility: 'Provide an accurate title and a meaningful fallback when provider content is blocked.',
  }),
  primitiveEntry({
    id: 'base.map',
    name: 'Map',
    description: 'A consent-delayed OpenStreetMap embed.',
    category: 'Interactive',
    icon: 'layout-solid',
    moduleId: 'base.provider-embed',
    tags: ['map', 'openstreetmap', 'provider', 'consent'],
    fields: [
      { key: 'sourceUrl', label: 'OpenStreetMap URL', type: 'url', required: true },
      { key: 'title', label: 'Accessible title', type: 'text', required: true },
      { key: 'fallbackText', label: 'Fallback text', type: 'text', required: true },
    ],
    preset: {
      id: 'openstreetmap',
      name: 'OpenStreetMap',
      values: {
        adapterId: 'maps.openstreetmap',
        kind: 'map',
        title: 'Map',
        fallbackText: 'Map unavailable.',
      },
    },
    requirements: {
      capabilities: [],
      providerAdapters: ['maps.openstreetmap'],
      plugins: [],
    },
    accessibilityChecks: [providerFallbackCheck()],
    usage: 'Paste an OpenStreetMap export URL from the approved provider origin.',
    accessibility: 'Use a title that identifies the location and provide the address in ordinary page text.',
  }),
  primitiveEntry({
    id: 'base.tab-panel',
    name: 'Tab Panel',
    description: 'One labelled panel inside Tabs.',
    category: 'Interactive',
    icon: 'layout-solid',
    moduleId: 'base.tab-panel',
    tags: ['tab', 'panel', 'interactive', 'form'],
    fields: [
      { key: 'tabId', label: 'Tab ID', type: 'text', required: true, advanced: true },
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'selected', label: 'Selected initially', type: 'boolean', required: false },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: ['base.tabs'],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Add one labelled content region to Tabs.',
    accessibility: 'Use a short unique label; all panels remain visible when JavaScript is unavailable.',
  }),
  primitiveEntry({
    id: 'base.accordion-item',
    name: 'Accordion Item',
    description: 'One native disclosure section inside an Accordion.',
    category: 'Interactive',
    icon: 'list-box-solid',
    moduleId: 'base.accordion-item',
    tags: ['accordion', 'details', 'summary', 'form'],
    fields: [
      { key: 'title', label: 'Summary', type: 'text', required: true },
      { key: 'open', label: 'Open initially', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: ['base.accordion'],
    accessibilityChecks: [accessibleNameCheck('title')],
    usage: 'Add one independently expandable section.',
    accessibility: 'Write a specific summary that identifies the hidden content.',
  }),
  ...BUILT_IN_VISUAL_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_DESIGN_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_INTERACTIVE_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_PATTERN_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_FORM_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_FORM_PATTERN_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_FORM_VISUAL_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_CAPABILITY_COMPONENT_LIBRARY_ENTRIES,
  ...BUILT_IN_CANONICAL_VISUAL_COMPONENT_LIBRARY_ENTRIES,
]

export function registerBuiltInComponentLibraryEntries(): void {
  for (const entry of BUILT_IN_COMPONENT_LIBRARY_ENTRIES) {
    componentLibraryRegistry.registerOrReplace(entry)
  }
}

registerBuiltInComponentLibraryEntries()
