import type { ComponentLibraryEntry } from '@core/component-library'
import {
  behaviorCheck,
  patternEntry,
} from './componentLibraryDefinitions'
import {
  CHECKBOX_GROUP,
  FORM_ACCORDION,
  FORM_TABS,
  PANEL,
  PREVIOUS_NEXT_ACTIONS,
  RADIO_GROUP,
  SUMMARY_REVIEW,
  TERMS,
  WIZARD,
} from './componentLibraryFormPatterns'

const formPatternParents = ['base.form-container', 'base.form-step']

export const BUILT_IN_FORM_PATTERN_COMPONENT_LIBRARY_ENTRIES:
readonly ComponentLibraryEntry[] = [
  patternEntry({
    id: 'base.form-panel',
    name: 'Panel',
    description: 'A titled semantic group for related form content.',
    category: 'Forms',
    icon: 'layout-solid',
    patternId: PANEL.id,
    tags: ['form', 'panel', 'section', 'fields'],
    allowedParentEntryIds: formPatternParents,
    allowedChildEntryIds: [
      'base.form-field-group',
      'base.heading',
      'base.rich-text',
      'base.plain-text',
      'base.image',
      'base.form-actions',
    ],
    usage: 'Group fields that share one purpose under a concise title.',
    accessibility: 'Keep a logical source order and identify the section with its heading.',
  }),
  patternEntry({
    id: 'base.form-accordion',
    name: 'Form Accordion',
    description: 'Form-aware sections composed from native Accordion items.',
    category: 'Forms',
    icon: 'list-box-solid',
    patternId: FORM_ACCORDION.id,
    tags: ['form', 'accordion', 'sections', 'validation'],
    allowedParentEntryIds: formPatternParents,
    allowedChildEntryIds: ['base.accordion-item'],
    accessibilityChecks: [
      behaviorCheck(
        'a11y.focus-contract',
        'focus',
        'Validation reveals a closed section before focusing its first invalid field.',
        'Keep each native summary specific and preserve validation-to-focus behavior.',
      ),
    ],
    usage: 'Use only when collapsing long form sections materially helps authors.',
    accessibility: 'Native details remain available without JavaScript and validation reveals errors.',
  }),
  patternEntry({
    id: 'base.form-tabs',
    name: 'Form Tabs',
    description: 'Form-aware sections using the shared Tabs keyboard and fallback contract.',
    category: 'Forms',
    icon: 'layout-columns',
    patternId: FORM_TABS.id,
    tags: ['form', 'tabs', 'sections', 'horizontal', 'vertical'],
    allowedParentEntryIds: formPatternParents,
    allowedChildEntryIds: ['base.tab-panel'],
    variants: [
      {
        id: 'horizontal',
        name: 'Horizontal',
        values: { orientation: 'horizontal' },
      },
      {
        id: 'vertical',
        name: 'Vertical',
        values: { orientation: 'vertical' },
      },
    ],
    accessibilityChecks: [
      behaviorCheck(
        'a11y.keyboard-contract',
        'keyboard',
        'Tabs provide arrow-key navigation and every panel stays visible without JavaScript.',
        'Use the orientation variant and preserve the shared Tabs runtime.',
      ),
      behaviorCheck(
        'a11y.focus-contract',
        'focus',
        'Validation activates a hidden panel before focusing its first invalid field.',
        'Keep validation state connected to the shared Tabs activation contract.',
      ),
    ],
    usage: 'Use one Form Tabs pattern and configure horizontal or vertical orientation in HTML view.',
    accessibility: 'Labels, keyboard behavior and progressive fallback come from shared Tabs.',
  }),
  patternEntry({
    id: 'base.checkbox-group',
    name: 'Checkbox Group',
    description: 'A fieldset of independently selectable Checkbox controls.',
    category: 'Forms',
    icon: 'checkbox-solid',
    patternId: CHECKBOX_GROUP.id,
    tags: ['form', 'checkbox', 'group', 'multiple choice'],
    allowedParentEntryIds: formPatternParents,
    allowedChildEntryIds: ['base.form-field-group'],
    usage: 'Use when zero or more answers may be selected.',
    accessibility: 'The fieldset legend states the shared question; every option keeps its own label.',
  }),
  patternEntry({
    id: 'base.radio-group',
    name: 'Radio Button Group',
    description: 'A fieldset of mutually exclusive Radio controls sharing one name.',
    category: 'Forms',
    icon: 'checkbox-solid',
    patternId: RADIO_GROUP.id,
    tags: ['form', 'radio', 'group', 'single choice'],
    allowedParentEntryIds: formPatternParents,
    allowedChildEntryIds: ['base.form-field-group'],
    usage: 'Use when exactly one visible option may be selected.',
    accessibility: 'The fieldset legend states the question and every radio shares one submission name.',
  }),
  patternEntry({
    id: 'base.previous-next-actions',
    name: 'Previous / Next Actions',
    description: 'A paired navigation action group for authored Wizard steps.',
    category: 'Forms',
    icon: 'send-solid',
    patternId: PREVIOUS_NEXT_ACTIONS.id,
    tags: ['form', 'wizard', 'previous', 'next', 'actions'],
    allowedParentEntryIds: ['base.form-step'],
    allowedChildEntryIds: ['base.previous-step', 'base.next-step'],
    accessibilityChecks: [
      behaviorCheck(
        'a11y.focus-contract',
        'focus',
        'Step navigation moves focus into the newly revealed section.',
        'Preserve source order and the shared Wizard runtime.',
      ),
    ],
    usage: 'Place at the end of a non-review Wizard step.',
    accessibility: 'Use clear action labels and keep all steps available without JavaScript.',
  }),
  patternEntry({
    id: 'base.form-summary-review',
    name: 'Summary / Review',
    description: 'A review step with editable summary content and final actions.',
    category: 'Forms',
    icon: 'file-text-solid',
    patternId: SUMMARY_REVIEW.id,
    tags: ['form', 'wizard', 'summary', 'review', 'confirmation'],
    allowedParentEntryIds: ['base.form-container'],
    usage: 'Summarise entered values before the final submission action.',
    accessibility: 'Keep edit actions specific and retain semantic headings for grouped answers.',
  }),
  patternEntry({
    id: 'base.terms-and-conditions',
    name: 'Terms and Conditions',
    description: 'Records agreement to an explicit versioned terms source.',
    category: 'Forms',
    icon: 'file-text-solid',
    patternId: TERMS.id,
    tags: ['form', 'terms', 'consent', 'versioned'],
    allowedParentEntryIds: formPatternParents,
    requirements: {
      capabilities: ['forms.versioned-consent'],
      providerAdapters: [],
      plugins: [],
    },
    usage: 'Configure the approved terms content and immutable version before enabling the capability.',
    accessibility: 'Use a visible required Checkbox label and never infer consent.',
  }),
  patternEntry({
    id: 'base.wizard',
    name: 'Wizard',
    description: 'A persistent multi-step CMS-native form with review and recovery.',
    category: 'Forms',
    icon: 'send-solid',
    patternId: WIZARD.id,
    tags: ['form', 'wizard', 'steps', 'draft', 'recovery'],
    requirements: {
      capabilities: ['forms.drafts'],
      providerAdapters: [],
      plugins: [],
    },
    allowedChildEntryIds: ['base.form-step'],
    accessibilityChecks: [
      behaviorCheck(
        'a11y.no-javascript-fallback',
        'form',
        'Every step remains visible and submit-capable when enhancement is unavailable.',
        'Keep authored steps in logical source order.',
      ),
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Save, recovery, conflict and expiry states are announced without stealing focus.',
        'Preserve the persistent draft runtime contract.',
      ),
    ],
    usage: 'Use only when cross-session recovery is enabled and the form warrants multiple steps.',
    accessibility: 'Keep step titles meaningful, validation local and recovery state explicit.',
  }),
]
