import type { ComponentLibraryEntry } from '@core/component-library'
import {
  accessibleNameCheck,
  behaviorCheck,
  draftBehaviorField,
  fieldIdField,
  fieldNameField,
  FORM_CONTROL_ACCESSIBILITY_CHECKS,
  formFieldParentEntryIds,
  formLayoutParentEntryIds,
  inputEntry,
  primitiveEntry,
  providerFallbackCheck,
  requiredField,
} from './componentLibraryDefinitions'

export const BUILT_IN_FORM_COMPONENT_LIBRARY_ENTRIES:
readonly ComponentLibraryEntry[] = [
  primitiveEntry({
    id: 'base.form-container',
    name: 'Form Container',
    description: 'A CMS-native or custom form boundary.',
    category: 'Forms',
    icon: 'file-text-solid',
    moduleId: 'base.form',
    container: true,
    tags: ['form', 'submission', 'container'],
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', required: true },
      { key: 'formId', label: 'Form ID', type: 'text', required: true },
      { key: 'targetTableId', label: 'Target collection', type: 'select', required: false },
      { key: 'successBehavior', label: 'Success behavior', type: 'select', required: true },
      { key: 'successMessage', label: 'Success message', type: 'text', required: false },
      { key: 'redirectUrl', label: 'Redirect destination', type: 'url', required: false },
      { key: 'draftMode', label: 'Draft recovery', type: 'select', required: true },
      { key: 'draftTtlDays', label: 'Draft expiry days', type: 'number', required: false },
    ],
    accessibilityChecks: [
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Submission success and errors require appropriate live announcements.',
        'Run the CMS form runtime announcement behavior tests.',
      ),
      behaviorCheck(
        'a11y.focus-contract',
        'focus',
        'Invalid submissions must reveal and focus the first invalid field.',
        'Run validation through nested disclosure fixtures and verify focus placement.',
      ),
    ],
    usage: 'Add approved fields and actions inside this form boundary.',
    accessibility: 'Provide labels, instructions, errors and a clear submission result.',
  }),
  primitiveEntry({
    id: 'base.form-field-group',
    name: 'Form Field Group',
    description: 'A governed layout boundary for one field, its label, help and error.',
    category: 'Forms',
    icon: 'layout-columns',
    moduleId: 'base.container',
    tags: ['form', 'field', 'group', 'layout'],
    preset: {
      id: 'field-group',
      name: 'Field group',
      values: { tag: 'div' },
    },
    allowedParentEntryIds: formLayoutParentEntryIds,
    allowedChildEntryIds: [
      'base.form-label',
      'base.text-input',
      'base.email-input',
      'base.telephone-input',
      'base.url-input',
      'base.number-input',
      'base.date-input',
      'base.text-area',
      'base.select',
      'base.checkbox',
      'base.switch',
      'base.radio',
      'base.form-help',
      'base.form-error',
      'base.file-attachment',
      'base.captcha',
      'base.plain-text',
      'base.image',
    ],
    usage: 'Group one control with its visible label, help and field error.',
    accessibility: 'Keep the label and any described help or error in the same group as the control.',
  }),
  primitiveEntry({
    id: 'base.form-actions',
    name: 'Form Actions',
    description: 'A governed layout boundary for submit and secondary actions.',
    category: 'Forms',
    icon: 'layout-columns',
    moduleId: 'base.container',
    tags: ['form', 'actions', 'submit', 'layout'],
    preset: {
      id: 'actions',
      name: 'Actions',
      values: { tag: 'div' },
    },
    allowedParentEntryIds: formLayoutParentEntryIds,
    allowedChildEntryIds: [
      'base.submit',
      'base.reset-button',
      'base.save-draft',
      'base.delete-draft',
      'base.next-step',
      'base.previous-step',
      'base.link',
      'base.form-message',
      'base.form-error',
    ],
    usage: 'Group the primary submit control and any secondary link at the end of a form.',
    accessibility: 'Keep the primary action clear and preserve a predictable keyboard order.',
  }),
  primitiveEntry({
    id: 'base.form-step',
    name: 'Form Step',
    description: 'A recoverable, progressively enhanced wizard step.',
    category: 'Forms',
    icon: 'layout-columns',
    moduleId: 'base.form-step',
    container: true,
    tags: ['form', 'wizard', 'step', 'review'],
    fields: [
      { key: 'stepId', label: 'Step ID', type: 'text', required: true },
      { key: 'title', label: 'Step title', type: 'text', required: true },
      { key: 'review', label: 'Review step', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: ['base.form-container'],
    usage: 'Place fields and actions inside ordered steps. Without JavaScript every step remains visible.',
    accessibility: 'Give every step a useful title and preserve logical source order.',
  }),
  primitiveEntry({
    id: 'base.save-draft',
    name: 'Save Draft',
    description: 'Persist recoverable form progress across sessions or devices.',
    category: 'Forms',
    icon: 'send-solid',
    moduleId: 'base.form-draft-action',
    tags: ['form', 'draft', 'save', 'recovery'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
    ],
    preset: {
      id: 'save-draft',
      name: 'Save draft',
      values: { action: 'save-draft', label: 'Save draft' },
    },
    allowedParentEntryIds: ['base.form-container', 'base.form-step', 'base.form-actions'],
    requirements: {
      capabilities: ['forms.drafts'],
      providerAdapters: [],
      plugins: [],
    },
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Use only on a form configured for Persistent recovery. The capability remains unavailable while server persistence is disabled.',
    accessibility: 'Announce saved, offline, conflict and failure states without moving focus.',
  }),
  primitiveEntry({
    id: 'base.delete-draft',
    name: 'Delete Draft',
    description: 'Delete the current persistent recovery record.',
    category: 'Forms',
    icon: 'warning-diamond-solid',
    moduleId: 'base.form-draft-action',
    tags: ['form', 'draft', 'delete', 'privacy'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
    ],
    preset: {
      id: 'delete-draft',
      name: 'Delete draft',
      values: { action: 'delete-draft', label: 'Delete saved draft' },
    },
    allowedParentEntryIds: ['base.form-container', 'base.form-step', 'base.form-actions'],
    requirements: {
      capabilities: ['forms.drafts'],
      providerAdapters: [],
      plugins: [],
    },
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Offer a direct privacy control beside Save Draft.',
    accessibility: 'Use an explicit label and announce successful deletion or revision conflicts.',
  }),
  primitiveEntry({
    id: 'base.next-step',
    name: 'Next Step',
    description: 'Move to the next authored form step.',
    category: 'Forms',
    icon: 'send-solid',
    moduleId: 'base.form-draft-action',
    tags: ['form', 'wizard', 'next'],
    fields: [{ key: 'label', label: 'Label', type: 'text', required: true }],
    preset: {
      id: 'next-step',
      name: 'Next step',
      values: { action: 'next-step', label: 'Next' },
    },
    allowedParentEntryIds: ['base.form-step', 'base.form-actions'],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Advance in source order; all steps remain available when JavaScript is absent.',
    accessibility: 'Move focus into the newly revealed step.',
  }),
  primitiveEntry({
    id: 'base.previous-step',
    name: 'Previous Step',
    description: 'Move to the previous authored form step.',
    category: 'Forms',
    icon: 'send-solid',
    moduleId: 'base.form-draft-action',
    tags: ['form', 'wizard', 'previous'],
    fields: [{ key: 'label', label: 'Label', type: 'text', required: true }],
    preset: {
      id: 'previous-step',
      name: 'Previous step',
      values: { action: 'previous-step', label: 'Previous' },
    },
    allowedParentEntryIds: ['base.form-step', 'base.form-actions'],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Return to the previous authored step without submitting.',
    accessibility: 'Move focus into the newly revealed step.',
  }),
  primitiveEntry({
    id: 'base.form-label',
    name: 'Label',
    description: 'A visible label for a form control.',
    category: 'Forms',
    icon: 'text-start-t',
    moduleId: 'base.label',
    tags: ['form', 'label'],
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'targetMode', label: 'Target', type: 'select', required: true, advanced: true },
      { key: 'targetId', label: 'Target ID', type: 'text', required: false, advanced: true },
    ],
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: [accessibleNameCheck('text')],
    usage: 'Place immediately before the control it describes.',
    accessibility: 'Use visible, specific labels; placeholders do not replace labels.',
  }),
  inputEntry('base.text-input', 'Text Input', 'text', 'General short text.'),
  inputEntry('base.email-input', 'Email Input', 'email', 'An email address.'),
  inputEntry('base.telephone-input', 'Telephone Input', 'tel', 'A telephone number.'),
  inputEntry('base.url-input', 'URL Input', 'url', 'A web address.'),
  inputEntry('base.number-input', 'Number Input', 'number', 'A numeric value.'),
  inputEntry('base.date-input', 'Date Input', 'date', 'A calendar date.'),
  primitiveEntry({
    id: 'base.hidden-field',
    name: 'Hidden Field',
    description: 'A fixed or context-derived value submitted without a visible control.',
    category: 'Forms',
    icon: 'text-start-t',
    moduleId: 'base.input',
    tags: ['form', 'field', 'hidden', 'metadata'],
    fields: [
      fieldIdField,
      fieldNameField,
      { key: 'value', label: 'Value', type: 'text', required: true },
      draftBehaviorField,
    ],
    preset: {
      id: 'hidden',
      name: 'Hidden field',
      values: { inputType: 'hidden' },
    },
    allowedParentEntryIds: formLayoutParentEntryIds,
    usage: 'Use only for non-secret fixed metadata that the server will validate independently.',
    accessibility: 'Hidden fields have no visual or assistive-technology interface and must not carry instructions.',
  }),
  primitiveEntry({
    id: 'base.text-area',
    name: 'Text Area',
    description: 'A multi-line form input.',
    category: 'Forms',
    icon: 'text-start-t',
    moduleId: 'base.textarea',
    tags: ['form', 'field', 'multiline'],
    fields: [
      fieldIdField,
      fieldNameField,
      { key: 'placeholder', label: 'Placeholder', type: 'text', required: false },
      requiredField,
      draftBehaviorField,
      { key: 'rows', label: 'Rows', type: 'number', required: true },
    ],
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: FORM_CONTROL_ACCESSIBILITY_CHECKS,
    usage: 'Use for responses that may need more than one line.',
    accessibility: 'Pair with a visible Label and concise help text when needed.',
  }),
  primitiveEntry({
    id: 'base.select',
    name: 'Select',
    description: 'A select control containing approved options.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.select',
    tags: ['form', 'select', 'options'],
    fields: [fieldIdField, fieldNameField, requiredField, draftBehaviorField],
    allowedParentEntryIds: formFieldParentEntryIds,
    allowedChildEntryIds: ['base.option', 'base.option-group'],
    accessibilityChecks: FORM_CONTROL_ACCESSIBILITY_CHECKS,
    usage: 'Use when one or more choices come from a controlled option set.',
    accessibility: 'Pair with a visible Label and keep option labels concise.',
  }),
  primitiveEntry({
    id: 'base.option',
    name: 'Option',
    description: 'One selectable value inside a Select.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.option',
    tags: ['form', 'select', 'option'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: ['base.select', 'base.option-group'],
    usage: 'Add one author-facing choice to a Select.',
    accessibility: 'Use a distinct label that communicates the choice.',
  }),
  primitiveEntry({
    id: 'base.option-group',
    name: 'Option Group',
    description: 'A labelled group of related Select options.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.option-group',
    tags: ['form', 'select', 'group'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: ['base.select'],
    allowedChildEntryIds: ['base.option'],
    usage: 'Group a longer option list into meaningful labelled sections.',
    accessibility: 'Use a short group label that distinguishes its options.',
  }),
  primitiveEntry({
    id: 'base.checkbox',
    name: 'Checkbox',
    description: 'A form control for an independent yes/no choice.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.checkbox',
    tags: ['form', 'checkbox', 'choice'],
    fields: [
      fieldIdField,
      fieldNameField,
      { key: 'value', label: 'Value', type: 'text', required: true },
      { key: 'checked', label: 'Checked', type: 'boolean', required: false },
      requiredField,
      draftBehaviorField,
    ],
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: FORM_CONTROL_ACCESSIBILITY_CHECKS,
    usage: 'Use for a choice that can be selected independently.',
    accessibility: 'Pair with a visible label describing the selected state.',
  }),
  primitiveEntry({
    id: 'base.switch',
    name: 'Switch',
    description: 'An on/off choice backed by the canonical checkbox control.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.checkbox',
    tags: ['form', 'checkbox', 'switch', 'toggle'],
    fields: [
      fieldIdField,
      fieldNameField,
      { key: 'value', label: 'Enabled value', type: 'text', required: true },
      { key: 'checked', label: 'Enabled initially', type: 'boolean', required: false },
      requiredField,
      draftBehaviorField,
    ],
    preset: {
      id: 'switch',
      name: 'Switch',
      values: { value: 'on', checked: false },
    },
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: FORM_CONTROL_ACCESSIBILITY_CHECKS,
    usage: 'Use for a setting whose effect is clear and immediate; otherwise use Checkbox.',
    accessibility: 'Pair with a visible label that describes the enabled state.',
  }),
  primitiveEntry({
    id: 'base.radio',
    name: 'Radio',
    description: 'One mutually exclusive choice in a radio group.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.radio',
    tags: ['form', 'radio', 'choice'],
    fields: [
      fieldIdField,
      fieldNameField,
      { key: 'value', label: 'Value', type: 'text', required: true },
      { key: 'checked', label: 'Checked', type: 'boolean', required: false },
      requiredField,
      draftBehaviorField,
    ],
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: FORM_CONTROL_ACCESSIBILITY_CHECKS,
    usage: 'Use with other Radio entries sharing one submission name.',
    accessibility: 'Group related radios under a visible question or fieldset legend.',
  }),
  primitiveEntry({
    id: 'base.submit',
    name: 'Submit Button',
    description: 'Submits the containing form.',
    category: 'Forms',
    icon: 'send-solid',
    moduleId: 'base.submit',
    tags: ['form', 'submit', 'action'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    allowedParentEntryIds: [
      'base.form-container',
      'base.form-actions',
    ],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Place once near the end of a form.',
    accessibility: 'Use a label that clearly states what will be submitted.',
  }),
  primitiveEntry({
    id: 'base.reset-button',
    name: 'Reset Button',
    description: 'Resets the containing form through the shared form-action module.',
    category: 'Forms',
    icon: 'warning-diamond-solid',
    moduleId: 'base.submit',
    tags: ['form', 'reset', 'action', 'clear'],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'disabled', label: 'Disabled', type: 'boolean', required: false },
    ],
    preset: {
      id: 'reset',
      name: 'Reset',
      values: { action: 'reset', label: 'Reset form' },
    },
    allowedParentEntryIds: [
      'base.form-container',
      'base.form-actions',
    ],
    accessibilityChecks: [accessibleNameCheck('label')],
    usage: 'Use sparingly and clearly distinguish reset from submission.',
    accessibility: 'Use an explicit label; consider confirmation when reset would discard substantial work.',
  }),
  primitiveEntry({
    id: 'base.form-message',
    name: 'Form Status',
    description: 'A submission status or result message for a form.',
    category: 'Forms',
    icon: 'warning-diamond-solid',
    moduleId: 'base.form-message',
    tags: ['form', 'status', 'error', 'success'],
    fields: [
      { key: 'kind', label: 'Message type', type: 'select', required: true },
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'formId', label: 'Form ID', type: 'text', required: false, advanced: true },
    ],
    preset: {
      id: 'status',
      name: 'Status',
      values: { kind: 'status' },
    },
    allowedParentEntryIds: [
      'base.form-container',
      'base.form-actions',
    ],
    accessibilityChecks: [
      accessibleNameCheck('text'),
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Submission status changes must be announced without unnecessary focus movement.',
        'Run the form runtime announcement and focus behavior tests.',
      ),
    ],
    usage: 'Explain form status or the result of a submission.',
    accessibility: 'Status messages must be concise and announced without moving focus unnecessarily.',
  }),
  primitiveEntry({
    id: 'base.form-help',
    name: 'Field Help',
    description: 'Persistent instructions associated with one form control.',
    category: 'Forms',
    icon: 'content-text',
    moduleId: 'base.form-message',
    tags: ['form', 'field', 'help', 'description'],
    fields: [
      fieldIdField,
      { key: 'text', label: 'Help text', type: 'text', required: true },
    ],
    preset: {
      id: 'help',
      name: 'Field help',
      values: { kind: 'help' },
    },
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: [
      accessibleNameCheck('text'),
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Field help must be connected through the control description.',
        'Verify aria-describedby includes the authored help message.',
      ),
    ],
    usage: 'Add concise instructions that remain visible before and after validation.',
    accessibility: 'The form runtime associates this text through aria-describedby.',
  }),
  primitiveEntry({
    id: 'base.form-error',
    name: 'Field Error',
    description: 'A validation message associated with one form control.',
    category: 'Forms',
    icon: 'warning-diamond-solid',
    moduleId: 'base.form-message',
    tags: ['form', 'field', 'error', 'validation'],
    fields: [
      fieldIdField,
      { key: 'text', label: 'Fallback error', type: 'text', required: false },
    ],
    preset: {
      id: 'error',
      name: 'Field error',
      values: { kind: 'error' },
    },
    allowedParentEntryIds: formFieldParentEntryIds,
    accessibilityChecks: [
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Field errors must be announced and associated with the invalid control.',
        'Verify aria-invalid, aria-errormessage, announcement and first-invalid focus behavior.',
      ),
    ],
    usage: 'Place beside the control whose server validation error it reports.',
    accessibility: 'The runtime marks the control invalid, announces the message and focuses the first invalid field.',
  }),
  primitiveEntry({
    id: 'base.file-attachment',
    name: 'File Attachment',
    description: 'A private, malware-scanned file upload for CMS-native forms.',
    category: 'Forms',
    icon: 'file-text-solid',
    moduleId: 'base.input',
    tags: ['form', 'file', 'attachment', 'upload', 'private'],
    fields: [
      fieldIdField,
      { key: 'name', label: 'Submission name', type: 'text', required: false },
      { key: 'accept', label: 'Accepted MIME types or extensions', type: 'text', required: false },
      { key: 'multiple', label: 'Allow multiple', type: 'boolean', required: false },
      { key: 'attachmentMaxFiles', label: 'Maximum files', type: 'number', required: true },
      { key: 'attachmentMaxBytes', label: 'Maximum bytes per file', type: 'number', required: true },
      { key: 'required', label: 'Required', type: 'boolean', required: false },
      draftBehaviorField,
    ],
    preset: {
      id: 'private-scanned',
      name: 'Private scanned attachment',
      values: {
        inputType: 'file',
        accept: '.pdf,.png,.jpg,.jpeg,.gif,.webp,.txt,.csv',
        multiple: false,
        attachmentMaxFiles: 1,
        attachmentMaxBytes: 10 * 1024 * 1024,
      },
    },
    allowedParentEntryIds: formFieldParentEntryIds,
    requirements: {
      capabilities: ['forms.attachments'],
      providerAdapters: [],
      plugins: [],
    },
    accessibilityChecks: [
      behaviorCheck(
        'a11y.announcement-contract',
        'form',
        'Upload progress, scan failures and retry state must be announced.',
        'Verify aggregate and per-file progress remain available to assistive technology.',
      ),
    ],
    usage: 'Bind to an Attachment data field. Files remain private, quarantined and unclaimable until the configured malware scanner returns clean.',
    accessibility: 'Provide a visible label, accepted-file guidance and a non-colour-only failure message.',
  }),
  primitiveEntry({
    id: 'base.captcha',
    name: 'CAPTCHA',
    description: 'A provider-neutral form verification boundary.',
    category: 'Forms',
    icon: 'checkbox-solid',
    moduleId: 'base.provider-embed',
    tags: ['form', 'captcha', 'verification', 'provider'],
    fields: [
      { key: 'title', label: 'Accessible title', type: 'text', required: true },
      { key: 'fallbackText', label: 'Unavailable message', type: 'text', required: true },
    ],
    preset: {
      id: 'hcaptcha',
      name: 'hCaptcha',
      values: {
        adapterId: 'captcha.hcaptcha',
        kind: 'captcha',
        title: 'Verification challenge',
        fallbackText: 'CAPTCHA verification is unavailable.',
      },
    },
    allowedParentEntryIds: formFieldParentEntryIds,
    requirements: {
      capabilities: ['forms.captcha'],
      providerAdapters: ['captcha.hcaptcha'],
      plugins: [],
    },
    accessibilityChecks: [providerFallbackCheck()],
    usage: 'Use only when the platform CAPTCHA capability and an approved adapter are healthy.',
    accessibility: 'Provide an alternate verification path and never claim availability while provider verification is unconfigured.',
  }),
]
