/** Public route contract shared by the pack test and visual parity verifier. */
export const creatorSignalPublicRouteSlugs = [
  'index',
  'products',
  'products/sales-pulse',
  'features',
  'pricing',
  'contact',
  'feedback',
  'wishlist',
  'early-access',
  'waitlist',
  'beta',
  'ask-a-question',
  'feature-request',
  'report-an-error',
  'legal/privacy',
  'legal/terms',
  'legal/billing',
  'legal/acceptable-use',
  'legal/browser-extension',
  'legal/cookies',
  'legal/dpa',
  'trust/security',
  'trust/subprocessors',
  'support',
  'help/account-data',
  'status',
] as const
