// The upstream artifact is an IIFE generated by @creator-signal/design-system.
// Importing it as the sole synchronous head entry preserves that behaviour
// while letting the Instatic plugin builder own the executable bundle.
import '../assets/design-system/theme-bootstrap.js'
