import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, resolve } from 'node:path'

interface DesignSystemLock {
  schema: 'creator-signal-design-system-lock/v1'
  source: {
    repository: string
    revision: string
    package: string
    packageVersion: string
    scopes: string[]
  }
  files: Array<{
    source: string
    target: string
    sha256: string
  }>
}

interface VerifyOptions {
  sourceRoot?: string
  revision?: string
  sync?: boolean
}

const repositoryRoot = resolve(import.meta.dir, '..')
const integrationRoot = resolve(repositoryRoot, 'integrations/creator-signal')
const lockPath = resolve(integrationRoot, 'design-system/lock.json')
const generatedCssPath = resolve(integrationRoot, 'design-system/foundation-css.ts')
const assetPlaceholder = '__CREATOR_SIGNAL_DESIGN_SYSTEM_ASSET_BASE__'

function assertRelativePath(path: string, label: string): void {
  if (isAbsolute(path) || path.split(/[\\/]/).includes('..')) {
    throw new Error(`${label} must stay within its declared root: ${path}`)
  }
}

async function sha256(path: string): Promise<string> {
  return createHash('sha256').update(await readFile(path)).digest('hex')
}

function git(sourceRoot: string, args: string[], allowFailure = false): string {
  const result = spawnSync('git', ['-C', sourceRoot, ...args], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  if (result.status !== 0 && !allowFailure) {
    throw new Error(`git ${args.join(' ')} failed: ${result.stderr.trim()}`)
  }
  return result.stdout.trim()
}

async function readLock(): Promise<DesignSystemLock> {
  const lock = JSON.parse(await readFile(lockPath, 'utf8')) as DesignSystemLock
  if (lock.schema !== 'creator-signal-design-system-lock/v1') {
    throw new Error(`Unsupported Creator Signal Design System lock schema: ${lock.schema}`)
  }
  if (!/^[0-9a-f]{40}$/.test(lock.source.revision)) {
    throw new Error('Creator Signal Design System lock must pin a full Git revision')
  }
  if (lock.files.length === 0) {
    throw new Error('Creator Signal Design System lock does not declare any files')
  }
  for (const file of lock.files) {
    assertRelativePath(file.source, 'Source path')
    assertRelativePath(file.target, 'Target path')
  }
  return lock
}

async function generateFoundationCss(lock: DesignSystemLock): Promise<string> {
  const foundationTargets = [
    'assets/design-system/tokens.css',
    'assets/design-system/typography.css',
    'assets/design-system/theme-runtime.css',
  ]
  const sections: string[] = []
  for (const target of foundationTargets) {
    if (!lock.files.some((file) => file.target === target)) {
      throw new Error(`Design System lock is missing foundation target: ${target}`)
    }
    const source = await readFile(resolve(integrationRoot, target), 'utf8')
    sections.push(source.replaceAll('url("./fonts/', `url("${assetPlaceholder}/fonts/`))
  }
  const css = sections.join('\n')
  return `// Generated by scripts/sync-creator-signal-design-system.ts. Do not edit.\n` +
    `import { creatorSignalDesignSystemAssetBaseUrl } from './contract'\n\n` +
    `const foundationCssTemplate = ${JSON.stringify(css)}\n\n` +
    `export const creatorSignalFoundationCss = foundationCssTemplate.replaceAll(\n` +
    `  '${assetPlaceholder}',\n` +
    `  creatorSignalDesignSystemAssetBaseUrl,\n` +
    `)\n`
}

function assertSourceRevision(
  sourceRoot: string,
  lock: DesignSystemLock,
  revision: string,
): void {
  const head = git(sourceRoot, ['rev-parse', 'HEAD'])
  git(sourceRoot, ['cat-file', '-e', `${revision}^{commit}`])
  const ancestor = spawnSync(
    'git',
    ['-C', sourceRoot, 'merge-base', '--is-ancestor', revision, head],
    { stdio: 'ignore' },
  )
  if (ancestor.status !== 0) {
    throw new Error(`Pinned revision ${revision} is not an ancestor of source HEAD ${head}`)
  }
  const relevantDiff = spawnSync(
    'git',
    ['-C', sourceRoot, 'diff', '--quiet', revision, head, '--', ...lock.source.scopes],
    { stdio: 'ignore' },
  )
  if (relevantDiff.status !== 0) {
    throw new Error(
      `Design System sources changed after ${revision}; sync from the intended authoritative revision`,
    )
  }
}

export async function verifyCreatorSignalDesignSystem(
  options: VerifyOptions = {},
): Promise<{ files: number; revision: string }> {
  const lock = await readLock()
  const sourceRoot = options.sourceRoot ? resolve(options.sourceRoot) : undefined
  if (options.sync && !sourceRoot) {
    throw new Error('--sync requires --source-root <sales-pulse checkout>')
  }

  let pinnedRevision = lock.source.revision
  if (sourceRoot) {
    pinnedRevision = options.revision ?? (options.sync
      ? git(sourceRoot, ['rev-parse', 'HEAD'])
      : lock.source.revision)
    if (!/^[0-9a-f]{40}$/.test(pinnedRevision)) {
      throw new Error('--revision must be a full 40-character Git SHA')
    }
    assertSourceRevision(sourceRoot, lock, pinnedRevision)
  }

  for (const file of lock.files) {
    const targetPath = resolve(integrationRoot, file.target)
    if (sourceRoot) {
      const sourcePath = resolve(sourceRoot, file.source)
      const sourceHash = await sha256(sourcePath)
      if (options.sync) {
        await mkdir(dirname(targetPath), { recursive: true })
        await copyFile(sourcePath, targetPath)
        file.sha256 = sourceHash
      } else if (sourceHash !== file.sha256) {
        throw new Error(`Authoritative source differs from the lock: ${file.source}`)
      }
    }

    if (!/^[0-9a-f]{64}$/.test(file.sha256)) {
      throw new Error(`Design System lock is missing a SHA-256 value for ${file.target}`)
    }
    const targetHash = await sha256(targetPath)
    if (targetHash !== file.sha256) {
      throw new Error(`Vendored Design System asset differs from the lock: ${file.target}`)
    }
  }

  if (options.sync) {
    lock.source.revision = pinnedRevision
    await writeFile(lockPath, `${JSON.stringify(lock, null, 2)}\n`, 'utf8')
    await writeFile(generatedCssPath, await generateFoundationCss(lock), 'utf8')
  } else {
    const expectedCss = await generateFoundationCss(lock)
    const actualCss = await readFile(generatedCssPath, 'utf8')
    if (actualCss !== expectedCss) {
      throw new Error('Generated Design System CSS adapter is stale; run the sync command')
    }
  }

  return { files: lock.files.length, revision: lock.source.revision }
}

function parseArguments(args: string[]): VerifyOptions {
  const options: VerifyOptions = {}
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index]
    if (argument === '--sync') {
      options.sync = true
    } else if (argument === '--source-root') {
      options.sourceRoot = args[++index]
      if (!options.sourceRoot) throw new Error('--source-root requires a path')
    } else if (argument === '--revision') {
      options.revision = args[++index]
      if (!options.revision) throw new Error('--revision requires a full Git SHA')
    } else {
      throw new Error(`Unknown argument: ${argument}`)
    }
  }
  return options
}

if (import.meta.main) {
  const result = await verifyCreatorSignalDesignSystem(parseArguments(Bun.argv.slice(2)))
  console.log(
    `Creator Signal Design System ${result.revision}: ${result.files} locked files verified.`,
  )
}
